### PR TITLE
Handle background-size on sprite images

### LINKED ISSUE #12: Retina images (pixel density)
What about pixel density? I have `@2x` images and I can't get assetgraph-sprite to calculate the position right. Could it perhaps read the `@2x` filename suffix or optional `background-size` rules from the CSS to determine image dimensions?

### PR DESCRIPTION
**Pull request by Munter**
Closes #12 

This is a work in progress. I still don't know how to programmatically test that the rendering is correct.

@silvenon could you link this branch up in your local setup so assetgraph-builder runs with it and see if your retina sprites get handled better?

### CODE REVIEW

**Comment by silvenon** [comment]
:+1:

**Comment by silvenon** [comment]
What do you think about not setting background size if the existing value is a keyword? For example if the value is `cover`, maybe it's safe to assume the user already took care of sizing?

**Comment by Munter** [comment]
I think any `background-size` of either a percentage, `cover`, `contain` or `inherit` can by definition not be sprited, since the logic would change completely when the image is replaced with a sprite sheet. It would probably be a good idea to detect this situation, ignore the image in the sprite and emit a warning so the user is aware.

**Comment by silvenon** [comment]
Oh, right, sprites cannot be fluid because of background position. My bad.

Yes, a warning would be nice.

**Pull request merged**
